version: 2

models:
  - name: has_docs_and_tests
    description: "isn't this description neat?"
    columns:
      - name: id
        description: primary key
        tests:
          - unique
          - not_null
      - name: type
        description: observation type
      - name: value
        description: observed value
      - name: date
        description: observed date
  - name: missing_docs_and_tests
