name: 'dave_snowflake_sandbox'
version: '1.0.0'
config-version: 2
profile: 'snowflake_sandbox'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:       
  - "target"
  - "dbt_packages"

on-run-end: "{{ load_metadata_on_run_end(table='dbt_run_results', schema=target.schema, database = target.database, create_schema = true) }}" 

models:
  dave_snowflake_sandbox:
    dbt_meta_testing:
      +required_docs: true
      +required_tests: {"unique.*|not_null": 1}

seeds:
  dave_snowflake_sandbox:
    +database: analytics
  