version: 2

models:
  - name: sample_data
    columns:
      - name: id
        # must declare data_type
        data_type: integer
        description: hello
        tests:
          - unique
      - name: color
        data_type: text
      - name: date_day
        data_type: date
