version: 2


models:
  - name: my_model
    config:
      # declare the model contracted
      contract: true
    columns:
      - name: id
        quote: true
        # must declare data_type
        data_type: integer
        description: hello
        # supply constraints on column id
        constraints: ['not null','primary key']
        # supply additional checks on column id
        constraints_check: (id > 0)
        tests:
          - unique
      - name: color
        data_type: text
      - name: date_day
        data_type: date

        