version: 2


models:
  - name: sample_data
    config:
      contract:
        enforced: true
    columns:
      - name: id
        quote: true
        # must declare data_type
        data_type: integer
        description: hello
        # supply constraints on column id
        constraints:
          - type: 'not null'
          - type: 'unique'
          - type: 'check'
            expression: (id > 0)
            warn_unenforced: true
            warn_unsupported: true
        tests:
          - unique
      - name: color
        data_type: text
      - name: date_day
        data_type: date

        