version: 2

models: 
  - name: sample_data
    description: "you've heard of data, sure, but what about fake data?"
    config:
      tags:
        - dave
        - data
    meta:
      ham: sandwich
    columns:
      - name: id
        tests:
          - unique 
          - not_null

  - name: stg_sample_data
    description: "you better believe it"
    config:
      tags:
        - dave
        - data
    meta:    
      eggs: benedict
    columns:
      - name: id
        tests:
          - unique 
          - not_null